// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tjhnnavoldugpairzyuz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqaG5uYXZvbGR1Z3BhaXJ6eXV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4NjQ2MzUsImV4cCI6MjA2MjQ0MDYzNX0.oubYaOVGb1F5Xj8WRBWh_6gSXtdoGeYHp2G4yvv32WE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);